/**
 * galeria.js — el archivo completo de fotos del taller.
 *
 * Son TODAS las fotos que mandó Rafael, no una selección: ambientes ya
 * instalados, piezas, componentes, el taller por dentro y las láminas con
 * cotas. Se pintan en `galeria.html`.
 *
 * El orden de los grupos no es casual — las duchas van primero, por pedido
 * del cliente: es la línea con la que empezó el taller y la que más se
 * busca. Dentro de cada grupo mandan las fotos de ambiente sobre las de
 * estudio, porque una pieza instalada vende más que una sobre fondo negro.
 *
 * Cada entrada es { base, grupo, ratio, alt }: `base` es el nombre del
 * archivo sin ancho ni formato (el sitio sirve 4 anchos × 3 formatos de cada
 * una), `ratio` es su proporción REAL — la rejilla es de mampostería y
 * respeta el alto de cada foto — y `alt` describe la foto para quien no la
 * ve. Muchas reusan la base que ya tenían en el catálogo: la misma foto no
 * se procesa ni se sirve dos veces.
 */

export const GRUPOS_GALERIA = [
  { slug: 'duchas', nombre: 'Duchas', bajada: 'Columnas, arcos y regaderas: la línea con la que empezó todo.' },
  { slug: 'grifos', nombre: 'Grifería y lavamanos', bajada: 'Grifos de muro y de cubierta, doblados a mano.' },
  { slug: 'toalleros', nombre: 'Toalleros y accesorios', bajada: 'Toalleros, ganchos y porta papel para completar el baño.' },
  { slug: 'piezas', nombre: 'Piezas y componentes', bajada: 'Manijas, escudos, abrazaderas y válvulas, una por una.' },
  { slug: 'taller', nombre: 'El taller', bajada: 'Cómo se hace: el cobre antes de llegar al muro.' },
  { slug: 'fichas', nombre: 'Medidas y láminas', bajada: 'Las cotas y las láminas del taller, para comparar antes de encargar.' },
];

export const GALERIA = [
  // ── Duchas (62) ──
  { base: '72272e7e-5670-4433-b7b3-288dbc6f8f30', grupo: 'duchas', ratio: '0.704 / 1', alt: 'Ducha de cobre con el agua abierta, contra un muro de ladrillo negro.' },
  { base: 'hero-ducha', grupo: 'duchas', ratio: '0.731 / 1', alt: 'Ducha de cobre instalada a la intemperie.' },
  { base: '632aabba-371f-4a34-9261-0e25a6368d4a', grupo: 'duchas', ratio: '0.679 / 1', alt: 'Dos duchas de cobre sobre columnas de piedra, en un patio empedrado.' },
  { base: 'g-ambiente-03', grupo: 'duchas', ratio: '0.695 / 1', alt: 'Ducha de cobre instalada en un baño de teja negra, con las manijas a media altura.' },
  { base: 'g-ambiente-05', grupo: 'duchas', ratio: '0.533 / 1', alt: 'Ducha de cobre en un patio exterior, sobre muro de piedra bajo la teja.' },
  { base: 'bd8725be-b680-417e-9a28-41281e37a4b8', grupo: 'duchas', ratio: '0.667 / 1', alt: 'Ducha de cobre con el agua cayendo, en un muro verde bajo la teja.' },
  { base: 'copia-de-7e70e78c-7fcc-4815-967f-add31944ce7b', grupo: 'duchas', ratio: '0.667 / 1', alt: 'Dos duchas de cobre con el agua abierta, en un muro de piedra.' },
  { base: 'g-ambiente-08', grupo: 'duchas', ratio: '0.750 / 1', alt: 'Ducha de cobre en un nicho de piedra, con la ventana abierta a la montaña.' },
  { base: 'g-ambiente-09', grupo: 'duchas', ratio: '0.667 / 1', alt: 'Ducha de cobre contra un muro de piedra, a cielo abierto.' },
  { base: 'g-ambiente-10', grupo: 'duchas', ratio: '0.714 / 1', alt: 'Ducha de cobre abierta, con el agua cayendo sobre piedra y plantas.' },
  { base: 'g-ambiente-11', grupo: 'duchas', ratio: '0.563 / 1', alt: 'Ducha de cobre en una esquina de piedra, junto a macetas de barro.' },
  { base: 'g-ambiente-12', grupo: 'duchas', ratio: '0.546 / 1', alt: 'Ducha de cobre junto a un espejo alargado, sobre muro de piedra.' },
  { base: '45a3fce2-afce-481e-963e-6a45578f627a', grupo: 'duchas', ratio: '0.752 / 1', alt: 'Ducha de cobre con el agua abierta, en un muro de piedra junto a una palmera.' },
  { base: 'ff2f6a97-4567-422d-8f17-cc62244a347e', grupo: 'duchas', ratio: '0.667 / 1', alt: 'Ducha de cobre con el agua cayendo, en un muro de ladrillo claro.' },
  { base: 'arco-colonial-doble-01-exterior', grupo: 'duchas', ratio: '0.667 / 1', alt: 'Ducha de cobre bajo el alero, en un muro de piedra con vista al campo.' },
  { base: 'g-ambiente-13', grupo: 'duchas', ratio: '0.729 / 1', alt: 'Ducha de cobre de noche, sobre un muro rematado en teja de barro.' },
  { base: 'g-ambiente-14', grupo: 'duchas', ratio: '1.778 / 1', alt: 'Ducha de cobre en un patio con jardinera iluminada.' },
  { base: '01b9503d-cdbd-4791-a529-48255ad63aaa', grupo: 'duchas', ratio: '0.778 / 1', alt: 'Ducha de cobre en arco montada sobre muro de piedra, dentro de una caseta de guadua, junto a un jardinera con flores rojas y rosadas y piso de mosaico floral azul y ocre.' },
  { base: '591c83f4-a968-4924-a1da-155af2652a21', grupo: 'duchas', ratio: '1.440 / 1', alt: 'Ducha de cobre con el agua abierta, montada en un muro de piedra.' },
  { base: 'g-ambiente-15', grupo: 'duchas', ratio: '0.667 / 1', alt: 'Ducha de cobre contra un muro de piedra, bajo el alero de teja, con jardín al lado.' },
  { base: 'arco-colonial-doble-04-piedra', grupo: 'duchas', ratio: '0.667 / 1', alt: 'Ducha de cobre a cielo abierto, sobre muro de piedra y piso de canto rodado.' },
  { base: 'g-ambiente-16', grupo: 'duchas', ratio: '0.911 / 1', alt: 'Ducha de cobre sobre una piscina de piedra rodeada de flores.' },
  { base: 'arco-colonial-doble-05-vano', grupo: 'duchas', ratio: '0.672 / 1', alt: 'Ducha de cobre en un muro de piedra, junto a la ventana abierta al campo.' },
  { base: 'g-ambiente-17', grupo: 'duchas', ratio: '0.604 / 1', alt: 'Ducha de cobre con el agua abierta, contra un muro de troncos.' },
  { base: 'g-ambiente-18', grupo: 'duchas', ratio: '0.750 / 1', alt: 'Ducha de cobre en un jardín tropical, con el agua cayendo.' },
  { base: 'g-ambiente-20', grupo: 'duchas', ratio: '0.574 / 1', alt: 'Ducha de cobre en un muro de piedra, con jardín y piso de canto rodado.' },
  { base: 'g-extra-13', grupo: 'duchas', ratio: '0.665 / 1', alt: 'Ducha doble de cobre en muro de piedra, con la altura de instalación de 2,40 m.' },
  { base: 'g-extra-16', grupo: 'duchas', ratio: '0.704 / 1', alt: 'Ducha de cobre con el agua abierta, contra un muro de ladrillo negro.' },
  { base: 'g-extra-18', grupo: 'duchas', ratio: '1.440 / 1', alt: 'Ducha de cobre al atardecer, montada sobre un cerco de troncos.' },
  { base: 'g-extra-19', grupo: 'duchas', ratio: '0.752 / 1', alt: 'Ducha de cobre en una esquina de piedra, junto a la ventana iluminada.' },
  { base: '9df2e8c8-1518-44a6-a2a2-bbb965bb0076', grupo: 'duchas', ratio: '0.667 / 1', alt: 'Ducha de cobre con la regadera abierta, sobre fondo oscuro.' },
  { base: 'arco-colonial-03-exterior', grupo: 'duchas', ratio: '0.667 / 1', alt: 'Arco Colonial en cobre.' },
  { base: 'tradicion-centenaria-08-bano-beige', grupo: 'duchas', ratio: '0.697 / 1', alt: 'Ducha de cobre en una pared beige de textura estriada.' },
  { base: 'tradicion-centenaria-06-nicho', grupo: 'duchas', ratio: '0.550 / 1', alt: 'Tradición Centenaria en cobre.' },
  { base: '63295635-580b-4133-b0a7-0c8194db9fc8', grupo: 'duchas', ratio: '0.784 / 1', alt: 'Arco Colonial en cobre.' },
  { base: 'g-taller-14', grupo: 'duchas', ratio: '1.446 / 1', alt: 'Varias duchas de cobre exhibidas sobre paneles de madera.' },
  { base: 'g-ficha-15', grupo: 'duchas', ratio: '0.846 / 1', alt: 'Comparación de las dos versiones: ducha con mezclador y ducha sencilla.' },
  { base: 'tradicion-centenaria-05-med', grupo: 'duchas', ratio: '1.500 / 1', alt: 'Tradición Centenaria en cobre.' },
  { base: '41763037-e53e-455a-b1f8-e55c4339bb60', grupo: 'duchas', ratio: '0.667 / 1', alt: 'Brazo de ducha en cobre con su regadera, sobre fondo oscuro.' },
  { base: 'b4dc22fb-a372-4fdc-8a2c-29470c4869bb', grupo: 'duchas', ratio: '0.667 / 1', alt: 'Tradición Centenaria en cobre.' },
  { base: 'tradicion-centenaria-09-detalle-regadera', grupo: 'duchas', ratio: '0.754 / 1', alt: 'Tradición Centenaria en cobre.' },
  { base: 'arco-colonial-05-bano-rustico', grupo: 'duchas', ratio: '0.752 / 1', alt: 'Arco Colonial en cobre.' },
  { base: 'tradicion-centenaria-07-med-altura', grupo: 'duchas', ratio: '0.714 / 1', alt: 'Tradición Centenaria en cobre.' },
  { base: 'g-extra-21', grupo: 'duchas', ratio: '0.667 / 1', alt: 'Ducha de cobre con el agua cayendo, sobre fondo oscuro.' },
  { base: 'b4107108-06f9-4501-ac96-f2dd09869e7a', grupo: 'duchas', ratio: '0.666 / 1', alt: 'Lámina del modelo Santa Bárbara: brazo doble en cobre sobre fondo de pátina.' },
  { base: 'copia-de-ad1a95aa-9a73-49e3-b928-53b5ae30df3e', grupo: 'duchas', ratio: '0.732 / 1', alt: 'Lámina de la Serie Artesanal 2026: ducha de cobre entre palmas.' },
  { base: 'g-ficha-05', grupo: 'duchas', ratio: '0.667 / 1', alt: 'Lámina de marca: duchas y accesorios en cobre para baños, hechos a mano.' },
  { base: 'g-ficha-08', grupo: 'duchas', ratio: '0.665 / 1', alt: 'Lámina de diámetros de regadera: 29 cm y 24 cm, una sobre otra.' },
  { base: 'g-ficha-14', grupo: 'duchas', ratio: '0.811 / 1', alt: 'Lámina de la ducha sencilla para piscina, con el agua abierta.' },
  { base: 'g-extra-04', grupo: 'duchas', ratio: '0.667 / 1', alt: 'Lámina de la Serie Artesanal: ducha de cobre con el agua abierta entre palmas.' },
  { base: 'g-extra-09', grupo: 'duchas', ratio: '1.500 / 1', alt: 'Lámina de la Serie Artesanal Tradición Centenaria, con la regadera y el agua.' },
  { base: 'g-extra-14', grupo: 'duchas', ratio: '0.762 / 1', alt: 'Lámina de la Serie Artesanal 2026: ducha de cobre entre vegetación.' },
  { base: 'g-extra-20', grupo: 'duchas', ratio: '0.667 / 1', alt: 'Lámina del modelo Camino Real: el brazo curvo con su regadera.' },
  { base: 'g-taller-03', grupo: 'duchas', ratio: '1.330 / 1', alt: 'Brazos de ducha con regadera cónica, recién terminados, sobre el banco del taller.' },
  { base: 'g-taller-06', grupo: 'duchas', ratio: '1.336 / 1', alt: 'Decenas de regaderas de cobre, cónicas y de martillado circular, en la mesa de producción.' },
  { base: 'g-taller-07', grupo: 'duchas', ratio: '0.490 / 1', alt: 'Exhibidor del taller con duchas, grifos y accesorios de cobre colgados.' },
  { base: 'g-taller-09', grupo: 'duchas', ratio: '0.568 / 1', alt: 'Brazos de ducha alineados en el banco de trabajo durante el armado.' },
  { base: 'g-taller-10', grupo: 'duchas', ratio: '1.778 / 1', alt: 'Regaderas terminadas y escudos apilados: dos vistas de la producción.' },
  { base: 'g-taller-11', grupo: 'duchas', ratio: '0.800 / 1', alt: 'Regaderas planas y brazos curvos de cobre agrupados durante la producción.' },
  { base: 'g-taller-12', grupo: 'duchas', ratio: '1.439 / 1', alt: 'Regaderas cónicas y de martillado circular sobre la mesa del taller.' },
  { base: '2fd6d0e7-442a-4b1e-a751-a1be69ef05a0', grupo: 'duchas', ratio: '1.500 / 1', alt: 'Exhibición del taller: varias duchas y grifos de cobre montados en el muro.' },
  { base: 'arco-colonial-doble-03-set', grupo: 'duchas', ratio: '0.800 / 1', alt: 'Ducha de cobre con el agua cayendo, sobre un muro de troncos apilados.' },
  // ── Grifería y lavamanos (27) ──
  { base: 'ffe2437e-c047-4c97-a0dd-73b631570249', grupo: 'grifos', ratio: '1.440 / 1', alt: 'Grifo de muro en cobre con el agua abierta y la cota de 26 cm de alcance.' },
  { base: 'g-ambiente-04', grupo: 'grifos', ratio: '0.662 / 1', alt: 'Lavamanos de piedra con grifo de muro en cobre, sobre pared de ladrillo.' },
  { base: 'df925cd9-98ed-48e3-8531-a0fda12efb40', grupo: 'grifos', ratio: '1.446 / 1', alt: 'Grifo de Muro en cobre.' },
  { base: 'grifo-de-arco-mezclador-02-producto', grupo: 'grifos', ratio: '1.377 / 1', alt: 'Grifo de muro de dos llaves en cobre, sobre fondo gris.' },
  { base: 'g-ambiente-06', grupo: 'grifos', ratio: '0.667 / 1', alt: 'Lavamanos de piedra con grifo alto de cobre y el agua cayendo.' },
  { base: 'g-ambiente-07', grupo: 'grifos', ratio: '0.768 / 1', alt: 'Baño claro con lavamanos de piedra y grifería de cobre en el muro.' },
  { base: '24dc10b1-2666-43f4-8507-5eca7bde46d8', grupo: 'grifos', ratio: '0.667 / 1', alt: 'Grifo de Muro en cobre.' },
  { base: '2dbc5343-fd4a-49cf-bed3-e50fb0689d3f', grupo: 'grifos', ratio: '0.667 / 1', alt: 'Grifo de Muro en cobre.' },
  { base: 'g-ficha-16', grupo: 'grifos', ratio: '0.665 / 1', alt: 'Grifo de muro en cobre con el agua abierta y la cota de 26 cm de alcance.' },
  { base: 'copia-de-c3a1b802-d40a-4109-9314-98cec7ba633e', grupo: 'grifos', ratio: '0.667 / 1', alt: 'Lavamanos de piedra sobre madera, con grifo de muro en cobre y pared de ladrillo.' },
  { base: 'g-pieza-32', grupo: 'grifos', ratio: '1.439 / 1', alt: 'Toallero de aros en cobre y un doble lavamanos con grifería de muro.' },
  { base: '4d5746d0-6508-4ccb-ae9b-5acff6127c13', grupo: 'grifos', ratio: '1.500 / 1', alt: 'Lavamanos de piedra con grifo alto de cobre y sus cotas.' },
  { base: 'g-ambiente-19', grupo: 'grifos', ratio: '1.432 / 1', alt: 'Doble lavamanos de piedra con dos grifos de muro en cobre.' },
  { base: 'g-ambiente-21', grupo: 'grifos', ratio: '0.750 / 1', alt: 'Baño con lavamanos de piedra, toallero de cobre y piso de mosaico.' },
  { base: 'g-pieza-16', grupo: 'grifos', ratio: '0.628 / 1', alt: 'Desagüe de lavamanos en cobre, con su tapa y el cuerpo desarmados.' },
  { base: 'g-ficha-12', grupo: 'grifos', ratio: '1.032 / 1', alt: 'Distancia de 25 cm entre las dos salidas de agua de un lavamanos.' },
  { base: 'g-pieza-26', grupo: 'grifos', ratio: '0.750 / 1', alt: 'Grifo de línea industrial en cobre y tubo blanco, montado sobre pared oscura.' },
  { base: 'g-pieza-28', grupo: 'grifos', ratio: '0.701 / 1', alt: 'Grifo de cuello curvo en cobre montado sobre una pared oscura.' },
  { base: '27df146b-e0e9-42bd-930a-0c066e05ceca', grupo: 'grifos', ratio: '0.667 / 1', alt: 'Grifo Cuello de Cisne en cobre.' },
  { base: 'g-pieza-30', grupo: 'grifos', ratio: '1.333 / 1', alt: 'Grifo de cuello curvo desarmado, con sus escudos y el empaque de repuesto.' },
  { base: 'g-pieza-31', grupo: 'grifos', ratio: '0.885 / 1', alt: 'Grifería de línea industrial en cobre y tubo blanco sobre piso de mosaico.' },
  { base: 'cuello-de-cisne-05-ambiente', grupo: 'grifos', ratio: '0.750 / 1', alt: 'Grifo Cuello de Cisne en cobre.' },
  { base: 'cuello-de-cisne-04-agua', grupo: 'grifos', ratio: '0.747 / 1', alt: 'Grifo Cuello de Cisne en cobre.' },
  { base: '5c8b60ac-26bb-48e1-85c3-3b5a72ce048f', grupo: 'grifos', ratio: '0.665 / 1', alt: 'Lámina del Grifo de Arco sobre lavamanos de piedra, con la cota de 26 cm.' },
  { base: '321f2173-099e-4655-b075-2e38725c851e', grupo: 'grifos', ratio: '1.500 / 1', alt: 'Lámina del Grifo Cuello de Cisne con sus cotas, sobre lavamanos de piedra.' },
  { base: 'grifo-de-arco-mezclador-01-rotulo', grupo: 'grifos', ratio: '0.740 / 1', alt: 'Lámina del Grifo de Arco con mezclador, sobre lavamanos de piedra oscura.' },
  { base: 'ffd8a538-86ee-4211-ae4a-14e304363d68', grupo: 'grifos', ratio: '0.613 / 1', alt: 'Lavamanos de cerámica esmaltada con grifo de cobre, sobre mesa de madera.' },
  // ── Toalleros y accesorios (14) ──
  { base: 'g-pieza-01', grupo: 'toalleros', ratio: '0.671 / 1', alt: 'Porta papel de cobre montado en un muro de piedra, con el rollo puesto.' },
  { base: 'porta-papel-04-repisa', grupo: 'toalleros', ratio: '0.682 / 1', alt: 'Porta papel de cobre montado en un muro oscuro, con el rollo puesto.' },
  { base: 'g-ambiente-02', grupo: 'toalleros', ratio: '0.685 / 1', alt: 'Tres ganchos de cobre en un muro de ladrillo, con una toalla blanca colgada.' },
  { base: 'acc378cd-9b6c-4e69-aea7-ef20033b4ba4', grupo: 'toalleros', ratio: '0.667 / 1', alt: 'Toallero de cobre bajo una repisa de piedra, con una toalla blanca colgada, un cuenco de piedra y una maceta de barro con una planta pequeña.' },
  { base: 'g-extra-10', grupo: 'toalleros', ratio: '1.440 / 1', alt: 'Toallero de cobre en tubería a la vista, montado en un baño de tono claro.' },
  { base: 'f41cbff2-6ed3-4f43-8457-65f5a9256261', grupo: 'toalleros', ratio: '1.538 / 1', alt: 'Porta Papel en cobre.' },
  { base: '16ce2158-2ed1-41a2-b241-8010383be0e2', grupo: 'toalleros', ratio: '0.474 / 1', alt: 'Toallero de Punto en cobre.' },
  { base: '659ac747-d6ab-4f29-aa2a-aa3e3de3f97b', grupo: 'toalleros', ratio: '1.506 / 1', alt: 'Toallero de Punto en cobre.' },
  { base: 'toallero-tradicional-03-grupo', grupo: 'toalleros', ratio: '1.500 / 1', alt: 'Toallero Tradicional en cobre.' },
  { base: '3cad3780-6bc7-49e1-8008-eb4611c5ae24', grupo: 'toalleros', ratio: '0.698 / 1', alt: 'Toallero Ovalado en cobre.' },
  { base: '2e12d1a1-7f30-4d30-af5e-b088e8653461', grupo: 'toalleros', ratio: '0.667 / 1', alt: 'Toallero Tradicional en cobre.' },
  { base: 'd4254363-e3d1-42c4-ae1f-e5c85009c7b6', grupo: 'toalleros', ratio: '0.679 / 1', alt: 'Toallero Tradicional en cobre.' },
  { base: 'g-ficha-03', grupo: 'toalleros', ratio: '1.080 / 1', alt: 'Lámina del Toallero de Punto con la cota de 8 cm de saliente.' },
  { base: '68ffe3ef-a077-483a-929f-5c205e74200f', grupo: 'toalleros', ratio: '0.750 / 1', alt: 'Lámina del Toallero Ovalado con sus cotas: 17 cm de alto por 24 cm de ancho.' },
  // ── Piezas y componentes (33) ──
  { base: 'g-pieza-03', grupo: 'piezas', ratio: '0.750 / 1', alt: 'Salida de muro en T, de tubo de cobre, sobre un tablón de madera oscura.' },
  { base: 'g-ambiente-01', grupo: 'piezas', ratio: '0.664 / 1', alt: 'Dos salidas de agua en cobre instaladas sobre una pared gris de textura estriada.' },
  { base: 'g-pieza-04', grupo: 'piezas', ratio: '1.137 / 1', alt: 'Dos salidas de muro en cobre montadas sobre un panel negro estriado.' },
  { base: 'g-pieza-09', grupo: 'piezas', ratio: '0.750 / 1', alt: 'Salida de muro en T sobre un tablón de madera envejecida.' },
  { base: 'g-pieza-15', grupo: 'piezas', ratio: '0.769 / 1', alt: 'Salida de muro en cobre montada sobre un panel negro de relieve geométrico.' },
  { base: 'g-pieza-20', grupo: 'piezas', ratio: '1.333 / 1', alt: 'Dos salidas de muro en cobre, en T y en codo, sobre madera envejecida.' },
  { base: 'g-pieza-07', grupo: 'piezas', ratio: '0.748 / 1', alt: 'Detalle del vástago estriado y el cuerpo de una válvula en cobre y bronce.' },
  { base: 'g-pieza-12', grupo: 'piezas', ratio: '0.703 / 1', alt: 'Dos cartuchos cerámicos, de fría y caliente, sobre madera oscura.' },
  { base: 'g-pieza-17', grupo: 'piezas', ratio: '0.787 / 1', alt: 'Tubo de cobre con abrazaderas soldadas a lo largo.' },
  { base: 'g-pieza-18', grupo: 'piezas', ratio: '0.754 / 1', alt: 'Dos vástagos de válvula sobre un tablón de madera envejecida.' },
  { base: 'g-pieza-22', grupo: 'piezas', ratio: '1.221 / 1', alt: 'Manija de cobre con su escudo, sobre fondo negro.' },
  { base: 'g-pieza-23', grupo: 'piezas', ratio: '0.750 / 1', alt: 'Detalle macro del vástago estriado de una válvula.' },
  { base: 'g-pieza-27', grupo: 'piezas', ratio: '0.750 / 1', alt: 'Codo con escudo de cobre junto al vástago y el buje desarmados.' },
  { base: 'g-pieza-29', grupo: 'piezas', ratio: '0.667 / 1', alt: 'Tornillo y buje plásticos del kit de montaje, sobre madera oscura.' },
  { base: 'g-pieza-33', grupo: 'piezas', ratio: '1.333 / 1', alt: 'Tornillo y buje del kit de montaje, sobre fondo oscuro.' },
  { base: 'g-extra-08', grupo: 'piezas', ratio: '0.639 / 1', alt: 'Cuerpo de válvula en cobre y bronce sobre madera oscura.' },
  { base: 'g-pieza-02', grupo: 'piezas', ratio: '1.466 / 1', alt: 'Manijas de cobre y una llave de paso agrupadas sobre fondo negro.' },
  { base: 'g-pieza-05', grupo: 'piezas', ratio: '0.666 / 1', alt: 'Abrazaderas de cobre para sujetar tubería, agrupadas sobre fondo negro.' },
  { base: 'g-pieza-06', grupo: 'piezas', ratio: '1.236 / 1', alt: 'Escudos de cobre apilados en pirámide sobre fondo negro.' },
  { base: 'g-pieza-19', grupo: 'piezas', ratio: '1.333 / 1', alt: 'Cuatro abrazaderas de cobre alineadas sobre fondo oscuro.' },
  { base: 'g-pieza-24', grupo: 'piezas', ratio: '1.333 / 1', alt: 'Tres abrazaderas de cobre alineadas sobre fondo negro.' },
  { base: 'g-extra-15', grupo: 'piezas', ratio: '0.765 / 1', alt: 'Cinco brazos de cobre con su codo, alineados sobre fondo negro.' },
  // ── El taller (10) ──
  { base: 'g-taller-04', grupo: 'taller', ratio: '0.556 / 1', alt: 'Aplicación del acabado con pistola sobre un brazo de cobre sujeto en el soporte.' },
  { base: 'g-taller-08', grupo: 'taller', ratio: '0.575 / 1', alt: 'Pistola de pintura aplicando el acabado a un brazo curvo de cobre.' },
  { base: 'g-taller-01', grupo: 'taller', ratio: '0.667 / 1', alt: 'Dos hileras de codos de cobre terminados, dispuestos en abanico sobre una mesa de madera.' },
  { base: 'g-taller-02', grupo: 'taller', ratio: '0.466 / 1', alt: 'Rafael Silva trabajando una pieza de cobre en su mesa de taller, frente a un muro de ladrillo.' },
  { base: 'rafael-retrato', grupo: 'taller', ratio: '0.752 / 1', alt: 'Rafael Silva soldando con soplete una unión de cobre en su taller, con camisa de cuadros, delantal de mezclilla y el estaño en la otra mano.' },
  { base: 'taller-soldadura', grupo: 'taller', ratio: '0.750 / 1', alt: 'Artesano con delantal de mezclilla soldando con soplete de propano una pieza de cobre en arco sujeta en una prensa de banco, con el alambre de estaño en la otra mano.' },
  { base: 'taller-elaboracion-manijas', grupo: 'taller', ratio: '0.564 / 1', alt: 'El artesano perfora un taco de madera sujeto en la prensa, con tres grupos de manijas de cobre terminadas sobre la mesa oscura.' },
  { base: 'taller-fundido', grupo: 'taller', ratio: '0.564 / 1', alt: 'Soplete fundiendo la rosca central de una base de regadera de cobre, con las regaderas de martillado circular al fondo.' },
  { base: 'g-extra-03', grupo: 'taller', ratio: '0.800 / 1', alt: 'Tubos de cobre cortados junto a los escudos empacados, listos para armar.' },
  { base: 'g-extra-07', grupo: 'taller', ratio: '0.564 / 1', alt: 'Rafael Silva perforando en la prensa, con las manijas de cobre terminadas al frente.' },
  // ── Medidas y láminas (14) ──
  { base: 'g-ficha-02', grupo: 'fichas', ratio: '0.667 / 1', alt: 'Dos manijas instaladas en un muro beige, rotuladas: manijas para regular el paso de agua.' },
  { base: 'g-ficha-01', grupo: 'fichas', ratio: '0.666 / 1', alt: 'Dos manijas de cobre en codo, rotuladas a mano: manijas para regular el paso de agua.' },
  { base: 'g-ficha-06', grupo: 'fichas', ratio: '0.749 / 1', alt: 'Vástago y manija de cobre con las partes señaladas: vástago estriado y manija.' },
  { base: 'g-ficha-07', grupo: 'fichas', ratio: '1.453 / 1', alt: 'Medición entre centros de un mezclador de dos llaves, sobre papel milimetrado.' },
  { base: 'g-ficha-09', grupo: 'fichas', ratio: '0.750 / 1', alt: 'Codo de cobre con el tornillo de ajuste señalado en la placa.' },
  { base: 'g-ficha-10', grupo: 'fichas', ratio: '0.667 / 1', alt: 'Manija de cobre para el paso de agua, con el tornillo de ajuste señalado.' },
  { base: 'g-ficha-11', grupo: 'fichas', ratio: '1.500 / 1', alt: 'Cuerpo mezclador de cobre medido con cinta métrica.' },
  { base: 'g-ficha-04', grupo: 'fichas', ratio: '1.500 / 1', alt: 'Lámina del modelo Arco Colonial: el arco de cobre completo sobre fondo oscuro.' },
  { base: '27c99ef6-e930-40bc-b6ad-173ff124c49f', grupo: 'fichas', ratio: '0.667 / 1', alt: 'Sello del taller: Rafael Silva, hecho a mano, Bucaramanga · Colombia.' },
  { base: 'g-ficha-13', grupo: 'fichas', ratio: '1.435 / 1', alt: 'Lámina del modelo Camino Real con la cota de 50 cm de proyección.' },
  { base: 'g-extra-01', grupo: 'fichas', ratio: '0.656 / 1', alt: 'Nota del taller sobre el desagüe PUSH para lavamanos y su acabado.' },
  { base: 'g-extra-06', grupo: 'fichas', ratio: '0.665 / 1', alt: 'Sello del taller: Rafael Silva, hecho a mano, Bucaramanga · Colombia.' },
  { base: 'g-extra-12', grupo: 'fichas', ratio: '0.707 / 1', alt: 'Lámina de diámetros de regadera: 29 cm y 24 cm.' },
  { base: 'g-extra-17', grupo: 'fichas', ratio: '0.667 / 1', alt: 'Sello del taller en tono cobre: Rafael Silva, hecho a mano, Bucaramanga.' },
  // ── Piezas doradas (Grival / bronce), al final de todo ──
  { base: 'g-pieza-08', grupo: 'piezas', ratio: '1.439 / 1', alt: 'Cartuchos cerámicos de agua fría y caliente junto a dos tees de bronce, sobre madera.' },
  { base: 'g-pieza-10', grupo: 'piezas', ratio: '1.440 / 1', alt: 'Cuerpo mezclador de dos llaves, en bronce y cobre, visto de frente.' },
  { base: 'g-pieza-11', grupo: 'piezas', ratio: '0.750 / 1', alt: 'Vástago de bronce de una válvula, de pie sobre fondo oscuro.' },
  { base: 'g-pieza-13', grupo: 'piezas', ratio: '0.750 / 1', alt: 'Tee de bronce roscada, vista de frente sobre fondo oscuro.' },
  { base: 'g-pieza-25', grupo: 'piezas', ratio: '0.879 / 1', alt: 'Cuerpos de válvula y cartuchos de agua fría y caliente sobre madera oscura.' },
  { base: 'mezclador-cuerpo-01', grupo: 'piezas', ratio: '1.440 / 1', alt: 'Cuerpo mezclador articulado en bronce, visto de frente.' },
  { base: 'g-pieza-14', grupo: 'piezas', ratio: '0.750 / 1', alt: 'Tee de bronce con la marca Grival grabada.' },
  { base: 'g-pieza-21', grupo: 'piezas', ratio: '0.750 / 1', alt: 'Dos tees de bronce Grival, una sobre otra.' },
  { base: 'g-extra-02', grupo: 'piezas', ratio: '0.750 / 1', alt: 'Cartuchos cerámicos Grival de agua fría y caliente, en su empaque.' },
  { base: 'g-extra-05', grupo: 'piezas', ratio: '0.750 / 1', alt: 'Tee de bronce junto a un cartucho cerámico Grival en su empaque.' },
  { base: 'g-extra-11', grupo: 'piezas', ratio: '0.750 / 1', alt: 'Dos cartuchos cerámicos Grival en su empaque.' },
];
